#!/bin/bash
if [ -z $1 ]
    then
    date=`date +%F`
else
    date=$1
fi
echo date = $date
export BUILD_SCRIPTS=/group/halld/Software/build_scripts
pushd /u/scratch/gluex/nightly/$date/Linux_CentOS7-x86_64-gcc4.8.5
source $BUILD_SCRIPTS/gluex_env_jlab.sh version_$date.xml
make -f $BUILD_SCRIPTS/Makefile_hdgeant4
